<ResizeWindow>:
    name: "resize"
    sizex: size_x
    sizey: size_y
    ratio: k_ratio
    ksize: k_size


    FloatLayout:

        Label:
            text:"File Size (px) : "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: 0.35, 0.15

        TextInput:
            id: size_x
            input_filter: 'float'
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.9}
            size_hint: 0.2, 0.10

        TextInput:
            id: size_y
            input_filter: 'float'
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            pos_hint: {"x":0.65, "top":0.9}
            size_hint: 0.2, 0.10

        Label:
            text:"Crop to Dimensions: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: 0.35, 0.15
        
        Label:
            text:"Keep Aspect Ratio: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.5}
            size_hint: 0.35, 0.15

        CheckBox:
            id: k_ratio
            pos_hint: {"x":0.5, "y":0.40}
            size_hint: 0.1 , 0.1
        
        CheckBox:
            id: k_size
            pos_hint: {"x":0.5, "y":0.60}
            size_hint: 0.1 , 0.1
        


        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.2
            font_size: (root.width**2 + root.height**2) / 13**4
            text: "Submit"
            on_release:
                root.manager.transition.direction = "up"
                root.loginBtn()

<MainWindow>:
    selected: listview
    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Select or Drag and Drop Files"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8}
                text: "Choose Files: "
                font_size: (root.width**2 + root.height**2) / 14**4
            
            Label:
                id: listview
                text: "Selected 6 Images"
                pos_hint: {"x":0.3, "top":0.6}
                size_hint: 0.5,0.12
                font_size: (root.width**2 + root.height**2) / 13**4



        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Submit"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "left"
                root.resize_settings()